// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEW_STATISTIC.Infrastructure.Data;

#nullable disable

namespace NEW_STATISTIC.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StatisticDbContext))]
    partial class StatisticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("NEW_STATISTIC.Infrastructure.Data.CandleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DensityUsdtPerMs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiffPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FirstTradePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastTradeTimeInWindowMs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange12hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange15mPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange1hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange1mPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange24hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange30mPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange3hPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange5mPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("QuoteVolume24hChange6hPct")
                        .HasColumnType("TEXT");

                    b.Property<long?>("QuoteVolume24hUpdatedMs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("QuoteVolume24hUsdt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalQuoteUsdt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TriggerTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WindowEndMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WindowStartMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "CreatedAt");

                    b.HasIndex("Symbol", "TriggerTimeMs");

                    b.ToTable("Candles", (string)null);
                });

            modelBuilder.Entity("NEW_STATISTIC.Infrastructure.Data.SimulationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CandleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OpenOffsetPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StopLossPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TakeProfitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandleId");

                    b.ToTable("Simulations", (string)null);
                });

            modelBuilder.Entity("NEW_STATISTIC.Infrastructure.Data.SimulationEntity", b =>
                {
                    b.HasOne("NEW_STATISTIC.Infrastructure.Data.CandleEntity", "Candle")
                        .WithMany("Simulations")
                        .HasForeignKey("CandleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candle");
                });

            modelBuilder.Entity("NEW_STATISTIC.Infrastructure.Data.CandleEntity", b =>
                {
                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
